# Generated by Django 3.1.7 on 2021-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='slug',
            field=models.CharField(editable=False, max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='slug',
            field=models.CharField(editable=False, max_length=255, verbose_name='Slug'),
        ),
    ]
