# Generated by Django 3.1.7 on 2021-04-04 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Urun ismi')),
                ('content', models.TextField(max_length=500, verbose_name='Urun Aciklamasi')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('stock_count', models.PositiveSmallIntegerField(verbose_name='stok_adeti')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Urun Fiyati')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
            ],
            options={
                'verbose_name': 'Urun',
                'verbose_name_plural': 'Urunler',
                'db_table': 'urunler',
            },
        ),
    ]
