# Generated by Django 3.1.7 on 2021-04-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20210404_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
