# Generated by Django 3.1.7 on 2021-04-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_book_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyBook',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('learning.book',),
        ),
    ]
