# Generated by Django 3.1.7 on 2021-04-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_proxybook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcompany',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gamecompany',
            name='author',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='book_ptr',
        ),
        migrations.DeleteModel(
            name='ProxyBook',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookCompany',
        ),
        migrations.DeleteModel(
            name='GameCompany',
        ),
        migrations.DeleteModel(
            name='Intro',
        ),
    ]
